MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = yes
RGBLIGHT_ENABLE = no
LTO_ENABLE = yes
RGB_MATRIX_ENABLE = no
RGB_MATRIX_DRIVER = WS2812
ENCODER_ENABLE = yes
OLED_ENABLE = yes
OLED_DRIVER = SSD1306
CAPS_WORD_ENABLE = yes
TAP_DANCE_ENABLE = yes

#debug
CONSOLE_ENABLE = yes
